### PR TITLE
Integrated Google Sheets Data

### PR DESCRIPTION
**Pull request by Sandesh1013**
Integrated Google Sheets Data for Timelines,Profiles,Projects.

### CODE REVIEW

**Review by Tanuj22 — COMMENTED** [review]
Looks good. Can you remove the `console.log` statements? Also make a file called `utilts.js` and keep the link of the spreadsheet there and you can just import it in all the files instead of repeating the link everywhere.

**Comment by Sandesh1013** [comment]
> Looks good. Can you remove the `console.log` statements? Also make a file called `utilts.js` and keep the link of the spreadsheet there and you can just import it in all the files instead of repeating the link everywhere.
Yeah I'll remove the console.log statements,but each tab has a separate link due to different sheets,so i think it'd require doing the same procedure in the 'utils.js' and sending a seperate array of data for each different view.

**Comment by Sandesh1013** [comment]
Yeah I'll remove the console.log statements,but each tab has a separate link due to different sheets,so i think it'd require doing the same procedure in the 'utils.js' and sending a seperate array of data for each different view.

**Comment by Tanuj22** [comment]
Okay. didn't notice the seperate tabs. Leave as it is

**Review by Tanuj22 — APPROVED** [review]

**Pull request merged**
